name: "Build Snapshot"

on: 
  - push
  - workflow_dispatch 

jobs:
  build-snapshot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v2
        with:
          image: tonistiigi/binfmt:latest
          platforms: arm64,arm

      - name: Setup Go
        uses: actions/setup-go@v3
        with: 
          go-version: '>=1.18.0'

      - name: grpc
        run: make grpc

      - name: goreleaser
        uses: goreleaser/goreleaser-action@v3
        with: 
          distribution: goreleaser
          version: latest
          args: release --snapshot --rm-dist --parallelism 1

      - name: Archive binaries
        uses: actions/upload-artifact@v3.1.0
        with: 
          name: "OliveTin-snapshot-${{ github.ref_name }}-${{ github.sha }}-dist"
          path: dist/OliveTin*.*

      - name: Archive integration tests
        uses: actions/upload-artifact@v3.1.0
        with: 
          name: integration-tests
          path: integration-tests
