name: "Build Tag"

on:
  push:
    tags: 
      - '*'

jobs:
  build-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: arm64,arm

      - name: Setup Go
        uses: actions/setup-go@v2
        with: 
          go-version: '^1.16.0'

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_KEY }}

      - name: grpc
        run: make grpc

      - name: goreleaser
        uses: goreleaser/goreleaser-action@v2
        with: 
          distribution: goreleaser
          version: latest
          args: release --rm-dist --parallelism 1 
        env: 
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Archive binaries
        uses: actions/upload-artifact@v2
        with: 
          name: dist
          path: dist/OliveTin*.*

      - name: Archive integration tests
        uses: actions/upload-artifact@v2
        with: 
          name: integration-tests
          path: integration-tests
